### ISSUE TITLE
Statistics where dropped between v1 and v2

### ISSUE THREAD

**Issue by michael-k** [django/channels_redis#127]
The statistics from PR django/channels_redis#24 did [not make it](https://github.com/django/channels_redis/commit/ff8c8e682fc08509bc2eaac7c51f5194b37b549d) to v2. They should be added again.

I'm not sure if I have time to tackle this in the near future.  If someone else wants to work on it, please do so.  Should I start working on it, I'll announce it here.

**Comment by andrewgodwin** [comment]
They were deliberately dropped due to the complexity innate in their implementation - at the moment, I don't particularly want to add them back in, unless they can somehow be separated out from the core code more cleanly and come with a full unit test suite.

If you want to work on that, then please do, but I'm going to close this issue for now as it's not something we're actively seeking work on - there's plenty else to do.
