### ISSUE TITLE
Channel names not unique 

### ISSUE THREAD

**Issue by luke777** [django/channels_redis#173]
It seems channel names are generated using a global instance of random, which can cause problems if the seed is reset.  For instance see:
https://groups.google.com/forum/#!msg/otree/0UEtVVA_98M/9nUo0nLPAgAJ
Presumably, there is also a small risk of non-uniqure names even if the seed is not reset.

**Comment by carltongibson** [comment]
Yes. There's a TODO for this:

https://github.com/django/channels_redis/blob/2dfc89289861cc642062daa4279ed4f3523647c3/channels_redis/core.py#L521-L531

Fancy taking it on?

**Comment by tarikki** [comment]
I wouldn't mind picking this up. 
So the approach would probably be just checking redis if the key exists and regenerate until it is unique?

**Comment by carltongibson** [comment]
Hi @tarikki. I guess something like that might be sufficient. (Thinking about how often such clashes may come up… Thinking about how we might test a fix… Etc 🙂)

**Comment by tarikki** [comment]
Sure. Let me try to throw a PR  your way early next week.

**Comment by carltongibson** [comment]
Hi @tarikki. Cool. There's a couple of fixes in, so if you do get it to me I'll look to do a release after that.

**Comment by tarikki** [comment]
Hi @carltongibson! 

Finally I had the time to look at this and it was not as straightforward as I thought. I looked at the code and it seems that the following is true:

1. Channel names are not stored in redis, but  as an attribute of the consumer in `self.channel_name`
2. The only time when redis has a hold of channel names is when the channels are part of a group or when there's inflight messages. This is really convenient for not flooding redis with data by only using it when there are messages to shuttle but makes the task of guaranteeing uniqueness harder.

So I see a couple of possible options to guarantee uniqueness:

1. When a channel name is created, store this in redis (for example, in a set). When a new channel name is created, check that the channel name does not exist in set and regenerate until name is unique. 

The obvious problem is what to do with all the generated names and when to delete them. A nice place to delete would the disconnect method in the consumer, but this would require editing the code in both channels_redis and channels, which is not ideal. Also in case of a non-clean exit, this would still leave some channel names in redis. 


2. Same as approach number one (store channel names in redis), but make this an optional setting and have it off by default. If the user knows that their setup requires more robust guarantees for uniqueness, they can enable it via the settings but they are responsible for flushing the names when they need to, perhaps via a helper function. 

Any ideas on how to proceed?

Of course this is based on my very limited familiarity with channels/channels_redis and there might be a way easier solution that I don't see :sweat_smile:

**Comment by carltongibson** [comment]
I’ve not given it any thought so, you’re the expert at this point. 🙂

I’d guess a good first step would be to document a subclass that implements stronger checking. Then, if that’s sufficiently clean, and we think popular, then we could make it an option (or even the default - the question here being, what’s the overhead?)

**Comment by tarikki** [comment]
Thanks for the advice. 

I'll create a PR for a subclass with stronger checking and a cleanup function for the names and let's see how that looks. It's always easier to get a clear idea of how stuff works when the code is staring you in the face :slightly_smiling_face: 

One path forward would be to first create a subclass with stronger checking in channels_redis, then if this looks good, add trying calling a 'delete channel name' function in the channels backend from the disconnect method in channels.

About the overhead: if we use the approach of storing used channel names in redis, under normal circumstances the overhead should be minimal because the clashes of non-unique names will be very rare. 

However when resetting the seed the overhead will go through the roof: let's say you create a million channel names and then reset the random seed. Then for each new subsequent channel name you create, you will have to go through all the previous million options before you hit a channel name that you have not used before :grimacing: 

Here cleaning up channel names on disconnect would help greatly.

**Comment by astutejoe** [comment]
@tarikki as using sorted sets only stores unique members I'll have to generate a random prefix to make sure it doesn't swallow copies, I'll make a PR for that as well, there are simple extremely fast solutions for that (harder solutions would be ones that are cryptographically secure)
