### ISSUE TITLE
migrate aioredis to v2.0

### ISSUE THREAD

**Issue by vvxhid** [django/channels_redis#285]
Connecting to redis is no longer done by calling await aioredis.create_pool(...). 
[link](https://aioredis.readthedocs.io/en/latest/migration/)

**Comment by dimonji** [comment]
Plus 1, any plans for upgrading airedis?

**Comment by LincolnPuzey** [comment]
This has been discussed in #268 and mentioned [here](https://github.com/django/channels_redis/issues/279#issuecomment-974782064).

Upgrading to 2.0 is the plan, just no one has done the work yet.

**Comment by ipmb** [comment]
This library is now part of the mainstream Redis library as of 4.2.0-rc1 https://github.com/redis/redis-py/pull/1899

**Comment by carltongibson** [comment]
Oh, that is good! 

Very happy to take a PR implementing this swap over.

**Comment by carltongibson** [comment]
It was added for the sentinel support. 🤔 @qeternity — Can you comment on the reasoning there? Thanks.

**Comment by qeternity** [comment]
Hi @ipmb - I'm not really sure what you're asking. The API for pools and connections is very similar (at least in aioredis 1.3.x). We can't use a raw redis connection with sentinel because a sentinel connection is actually two redis connections: one pubsub connection to a sentinel, and then a connection to the actual redis instance. This logic was all orchestrated by the aioredis sentinel pool. However, because the old layer (non pubsub) does not use any pooling, and marshals connections manually, we don't want to risk letting the sentinel connections in the pool grow, because we will end up having many pools.

All of this was done to make sentinel drop-in compatible with the non-pubsub layer.

**Comment by ipmb** [comment]
Yeah, it's not available here https://github.com/redis/redis-py/blob/c5d19b8571d2b15a29637f56a51b0da560072945/redis/asyncio/connection.py#L1379-L1538

I'm guessing we can iterate over the connections ourselves and verify they have all been closed.

**Comment by carltongibson** [comment]
This was done in #296 — will be in 4.0. 4.0.0b2 is available for testing now.
